/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardAffichesRouteImport } from './routes/dashboard.affiches'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardFamillesRouteImport } from './routes/dashboard.familles'
import { Route as DashboardPaiementsRouteImport } from './routes/dashboard.paiements'
import { Route as DashboardPlanificationsRouteImport } from './routes/dashboard.planifications'
import { Route as DashboardRapportsRouteImport } from './routes/dashboard.rapports'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as SuperadminAdminsRouteImport } from './routes/superadmin.admins'
import { Route as SuperadminCentresRouteImport } from './routes/superadmin.centres'
import { Route as SuperadminDemandesRouteImport } from './routes/superadmin.demandes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAffichesRoute = DashboardAffichesRouteImport.update({
  id: '/affiches',
  path: '/affiches',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFamillesRoute = DashboardFamillesRouteImport.update({
  id: '/familles',
  path: '/familles',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaiementsRoute = DashboardPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPlanificationsRoute = DashboardPlanificationsRouteImport.update({
  id: '/planifications',
  path: '/planifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRapportsRoute = DashboardRapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAdminsRoute = SuperadminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminCentresRoute = SuperadminCentresRouteImport.update({
  id: '/centres',
  path: '/centres',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminDemandesRoute = SuperadminDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => SuperadminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/dashboard/affiches': typeof DashboardAffichesRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/familles': typeof DashboardFamillesRoute
  '/dashboard/paiements': typeof DashboardPaiementsRoute
  '/dashboard/planifications': typeof DashboardPlanificationsRoute
  '/dashboard/rapports': typeof DashboardRapportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/centres': typeof SuperadminCentresRoute
  '/superadmin/demandes': typeof SuperadminDemandesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/dashboard/affiches': typeof DashboardAffichesRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/familles': typeof DashboardFamillesRoute
  '/dashboard/paiements': typeof DashboardPaiementsRoute
  '/dashboard/planifications': typeof DashboardPlanificationsRoute
  '/dashboard/rapports': typeof DashboardRapportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/centres': typeof SuperadminCentresRoute
  '/superadmin/demandes': typeof SuperadminDemandesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/dashboard/affiches': typeof DashboardAffichesRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/familles': typeof DashboardFamillesRoute
  '/dashboard/paiements': typeof DashboardPaiementsRoute
  '/dashboard/planifications': typeof DashboardPlanificationsRoute
  '/dashboard/rapports': typeof DashboardRapportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/superadmin/admins': typeof SuperadminAdminsRoute
  '/superadmin/centres': typeof SuperadminCentresRoute
  '/superadmin/demandes': typeof SuperadminDemandesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/superadmin'
    | '/dashboard/affiches'
    | '/dashboard/calendar'
    | '/dashboard/familles'
    | '/dashboard/paiements'
    | '/dashboard/planifications'
    | '/dashboard/rapports'
    | '/dashboard/settings'
    | '/superadmin/admins'
    | '/superadmin/centres'
    | '/superadmin/demandes'
    | '/dashboard/'
    | '/superadmin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacy'
    | '/dashboard/affiches'
    | '/dashboard/calendar'
    | '/dashboard/familles'
    | '/dashboard/paiements'
    | '/dashboard/planifications'
    | '/dashboard/rapports'
    | '/dashboard/settings'
    | '/superadmin/admins'
    | '/superadmin/centres'
    | '/superadmin/demandes'
    | '/dashboard'
    | '/superadmin'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/privacy'
    | '/superadmin'
    | '/dashboard/affiches'
    | '/dashboard/calendar'
    | '/dashboard/familles'
    | '/dashboard/paiements'
    | '/dashboard/planifications'
    | '/dashboard/rapports'
    | '/dashboard/settings'
    | '/superadmin/admins'
    | '/superadmin/centres'
    | '/superadmin/demandes'
    | '/dashboard/'
    | '/superadmin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/affiches': {
      id: '/dashboard/affiches'
      path: '/affiches'
      fullPath: '/dashboard/affiches'
      preLoaderRoute: typeof DashboardAffichesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/familles': {
      id: '/dashboard/familles'
      path: '/familles'
      fullPath: '/dashboard/familles'
      preLoaderRoute: typeof DashboardFamillesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/paiements': {
      id: '/dashboard/paiements'
      path: '/paiements'
      fullPath: '/dashboard/paiements'
      preLoaderRoute: typeof DashboardPaiementsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/planifications': {
      id: '/dashboard/planifications'
      path: '/planifications'
      fullPath: '/dashboard/planifications'
      preLoaderRoute: typeof DashboardPlanificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/rapports': {
      id: '/dashboard/rapports'
      path: '/rapports'
      fullPath: '/dashboard/rapports'
      preLoaderRoute: typeof DashboardRapportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/admins': {
      id: '/superadmin/admins'
      path: '/admins'
      fullPath: '/superadmin/admins'
      preLoaderRoute: typeof SuperadminAdminsRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/centres': {
      id: '/superadmin/centres'
      path: '/centres'
      fullPath: '/superadmin/centres'
      preLoaderRoute: typeof SuperadminCentresRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/demandes': {
      id: '/superadmin/demandes'
      path: '/demandes'
      fullPath: '/superadmin/demandes'
      preLoaderRoute: typeof SuperadminDemandesRouteImport
      parentRoute: typeof SuperadminRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAffichesRoute: typeof DashboardAffichesRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardFamillesRoute: typeof DashboardFamillesRoute
  DashboardPaiementsRoute: typeof DashboardPaiementsRoute
  DashboardPlanificationsRoute: typeof DashboardPlanificationsRoute
  DashboardRapportsRoute: typeof DashboardRapportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAffichesRoute: DashboardAffichesRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardFamillesRoute: DashboardFamillesRoute,
  DashboardPaiementsRoute: DashboardPaiementsRoute,
  DashboardPlanificationsRoute: DashboardPlanificationsRoute,
  DashboardRapportsRoute: DashboardRapportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminAdminsRoute: typeof SuperadminAdminsRoute
  SuperadminCentresRoute: typeof SuperadminCentresRoute
  SuperadminDemandesRoute: typeof SuperadminDemandesRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminAdminsRoute: SuperadminAdminsRoute,
  SuperadminCentresRoute: SuperadminCentresRoute,
  SuperadminDemandesRoute: SuperadminDemandesRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
